name: Cron Workflow

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  Cron_Job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cron First Step
        run: |
          echo "This is the first step of the cron job."
